# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    curl -Os https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
    unzip terraform_0.12.24_linux_amd64.zip terraform

    echo HOME=$HOME
    
    cat <<EOF > /home/vsts/.terraformrc
    credentials "app.terraform.io" {
      token = "$(TFE_TOKEN)"
    }
    EOF

    cat /home/vsts/.terraformrc
    terraform login
    terraform init
    terraform plan
    terraform apply
    echo See https://aka.ms/yaml
  displayName: 'Test Terraform'