# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    curl -Os https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
    unzip terraform_0.12.24_linux_amd64.zip terraform

    echo HOME=$HOME
    mkdir /home/vsts/.terraform.d
    cat <<EOF > /home/vsts/.terraform.d/credentials.tfrc.json
    {
    "credentials": {
    "app.terraform.io": {
      "token": "$(TFE_TOKEN)"
      }
    }
    EOF

    cat /home/marc/.terraform.d/credentials.tfrc.json

    terraform init
    terraform plan
    terraform apply
    echo See https://aka.ms/yaml
  displayName: 'Test Terraform'